import type { Metadata } from "next";
import "@/app/globals.css";
import { Toaster } from "@/components/ui/toaster";
import StudentNavBar from "@/components/StudentNavBar";
import ProfessorNavBar from "@/components/ProfessorNavBar";
import { getUserRole } from "@/lib/getUserRole";

export const metadata: Metadata = {
  title: "Usap",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userRole = await getUserRole();
  return (
    <html lang="en" className="">
      <body className={`bg-background text-foreground antialiased`}>
        {userRole === "PROFESSOR" ? <ProfessorNavBar /> : <StudentNavBar />}
        {children}
        <Toaster />
      </body>
    </html>
  );
}
