import type { Metadata } from "next";
import "./globals.css";
import SessionProviders from "@/components/SessionProviders";
export const metadata: Metadata = {
  title: "Usap",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className={`bg-background text-foreground antialiased`}>
        <SessionProviders>{children}</SessionProviders>
      </body>
    </html>
  );
}
