import type { Metadata } from "next";
import "@/app/globals.css";
import NavBar from "@/components/NavBar";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Usap",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className={`bg-background text-foreground antialiased`}>
        <NavBar />
        <p>Professor</p>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
